(define (problem PACKED-GROCERY)
(:domain GROCERY)
(:objects bleach nutella coke pepsi lipton - item)
(:init    (not (ontable bleach))  (not (ontable nutella))
		 (not (ontable coke)) (not (ontable pepsi))
		 (not (ontable lipton))
		(cleartop bleach) (cleartop nutella) (cleartop coke) (cleartop pepsi) (cleartop lipton)
		(clearright bleach) (clearright nutella) (clearright coke) (clearright pepsi) (clearright lipton) (clearleft bleach) (clearleft nutella) (clearleft coke) (clearleft pepsi) (clearleft lipton) (handempty))
(:goal  (and (ontable bleach) (toleft coke bleach)))
)